//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateAuthority.Tests.FullProjectTests.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertificateAuthority.Tests.FullProjectTests.Helpers.TestDataResource", typeof(TestDataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE REQUEST----- MIIEzzCCArcCAQAwczELMAkGA1UEBhMCUVExCzAJBgNVBAgMAlFRMQswCQYDVQQH DAJRUTELMAkGA1UECgwCUVExCzAJBgNVBAsMAlFRMREwDwYDVQQDDAhzdWJjZXJ0 MTEdMBsGCSqGSIb3DQEJARYOcXdlcXdlQHF3ZS5xd2UwggIiMA0GCSqGSIb3DQEB AQUAA4ICDwAwggIKAoICAQC+oNOAhdNLMeTkycQtmj3cD3jf0BqlPH4Rz7Q4EZtE Gh+x3dkBEMoZigj1WGgwc+A3eNEtr1gS3TTldld3J9S7xlBQWXOyvSMaMDtMJ5uT uiSWnH0Kn8sYHsyLb1Nibx7GvHPdmOIJHrm4XcLJmXAinaeLCcHOEqfwMBkTIeDG e4NOT3o6UjnuCaHam1vOf+fNPo/+1fZGBlp4imfQf5L8EDH9JGPlVFxQa1jNuM5t XhntNIOMiZxV0C2v7HRnn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CertificateRequest1 {
            get {
                return ResourceManager.GetString("CertificateRequest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE REQUEST----- MIIE1jCCAr4CAQAwejELMAkGA1UEBhMCcXcxCzAJBgNVBAgMAnF3MQswCQYDVQQH DAJxdzELMAkGA1UECgwCcXcxCzAJBgNVBAsMAnF3MRUwEwYDVQQDDAxjZXJ0UmVx dWVzdDIxIDAeBgkqhkiG9w0BCQEWEXF3ZUBxd2Vxd2Vxd2UucXdlMIICIjANBgkq hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxvT2sYqPjlMWfx3TxzaO6xRrqeiMuzuM xhxjbiL2g+v0T0uNT+nBRgvph6wGE2L8NsgVTsUS4tUo/PBx3DxmrFlZT4FEcIuk LIePUFgTyWmWRm/B69oomb0BiaoLPV+USS26OFkm+RPdc2vDXL23y38HNVmNeR7s P++B7uDUzjJmyqEFaPxGBbR/KakYAx/onMZNZymMwwe9Ly0DhHL9w9NG0hqQr6gO dCHPBItjaZv9yr6x4Zhsv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CertificateRequest2 {
            get {
                return ResourceManager.GetString("CertificateRequest2", resourceCulture);
            }
        }
    }
}
